---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-client
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["pods", "pods/log", "deployments", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-client
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-client
subjects:
- kind: ServiceAccount
  name: k8s-client
  namespace: devops