openapi: 3.0.0
info:
  title: K8S-client API company
  version: "1.0"
paths:
  "/ping":
    get:
      summary: Ping API (returns pong)
      responses:
        "200":
          description: OK
  "/namespace/list":
    get:
      summary: list namespaces
      responses:
        "200":
          description: OK
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
  "/namespace/create":
    post:
      description: create namespace
      requestBody:
        description: create namespace
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - namespace
              properties:
                namespace:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
  "/namespace/delete":
    post:
      description: delete namespace
      requestBody:
        description: delete namespace
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - namespace
              properties:
                namespace:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
  "/namespace/check":
    post:
      description: check namespace
      requestBody:
        description: check namespace
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - namespace
              properties:
                namespace:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
servers:
  - url: /api/v1
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-apikeyInfoFunc: k8s_client.controller.auth.apikey

security:
  - ApiKeyAuth: []
